name: Trigger Jenkins on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook to Jenkins
        run: |
          curl -X POST ${{ secrets.JENKINS_URL }} \
          -H "Content-Type: application/json" \
          -d '{"ref": "refs/heads/main"}'
